In [1]:
import pandas as pd

# 1. Merge both dataframes
# 2. Filter by Lg to = NHL and remove Lg column
# 3. Remove 'From' column
# 4. Filter "To" column to only show 2021 
# 5. Filter to only show the row with the max years
# 6. Remove columns: 'T', 'PTS%', 'Div', 'Conf', 'Champ'

In [2]:
url = 'https://www.hockey-reference.com/teams/'

In [3]:
#Extract
team_tables = pd.read_html(url)
team_tables

[                  Franchise   Lg  From    To  Yrs    GP     W     L      T  \
 0             Anaheim Ducks  NHL  1993  2021   27  2111   990   834  107.0
 1             Anaheim Ducks  NHL  2006  2021   15  1159   609   407    NaN
 2   Mighty Ducks of Anaheim  NHL  1993  2006   12   952   381   427  107.0
 3           Arizona Coyotes  NHL  1979  2021   41  3234  1335  1468  266.0
 4           Arizona Coyotes  NHL  2014  2021    7   536   214   262    NaN
 5           Phoenix Coyotes  NHL  1996  2014   17  1360   615   546   94.0
 6             Winnipeg Jets  NHL  1979  1996   17  1338   506   660  172.0
 7             Boston Bruins  NHL  1924  2021   96  6626  3241  2403  791.0
 8            Buffalo Sabres  NHL  1970  2021   50  3945  1805  1564  409.0
 9            Calgary Flames  NHL  1972  2021   48  3790  1765  1496  379.0
 10           Calgary Flames  NHL  1980  2021   40  3154  1497  1236  271.0
 11           Atlanta Flames  NHL  1972  1980    8   636   268   260  108.0
 12      Carolina Hurricanes  NHL  1979  2021   41  3232  1361  1434  263.0
 13      Carolina Hurricanes  NHL  1997  2021   23  1812   827   725   86.0
 14         Hartford Whalers  NHL  1979  1997   18  1420   534   709  177.0
 15       Chicago Blackhawks  NHL  1926  2021   94  6560  2812  2761  814.0
 16       Chicago Blackhawks  NHL  1986  2021   34  2674  1244  1060  197.0
 17      Chicago Black Hawks  NHL  1926  1986   60  3886  1568  1701  617.0
 18       Colorado Avalanche  NHL  1979  2021   41  3234  1504  1327  261.0
 19       Colorado Avalanche  NHL  1995  2021   25  1978  1007   728  101.0
 20         Quebec Nordiques  NHL  1979  1995   16  1256   497   599  160.0
 21    Columbus Blue Jackets  NHL  2000  2021   20  1568   678   698   33.0
 22             Dallas Stars  NHL  1967  2021   53  4171  1842  1708  459.0
 23             Dallas Stars  NHL  1993  2021   27  2109  1084   738  125.0
 24    Minnesota North Stars  NHL  1967  1993   26  2062   758   970  334.0
 25        Detroit Red Wings  NHL  1926  2021   94  6561  2989  2574  815.0
 26        Detroit Red Wings  NHL  1932  2021   88  6293  2891  2446  773.0
 27          Detroit Falcons  NHL  1930  1932    2    92    34    41   17.0
 28          Detroit Cougars  NHL  1926  1930    4   176    64    87   25.0
 29          Edmonton Oilers  NHL  1979  2021   41  3235  1469  1337  262.0
 30         Florida Panthers  NHL  1993  2021   27  2109   889   870  142.0
 31        Los Angeles Kings  NHL  1967  2021   53  4172  1754  1828  424.0
 32           Minnesota Wild  NHL  2000  2021   20  1567   759   599   55.0
 33       Montreal Canadiens  NHL  1917  2021  103  6787  3473  2302  837.0
 34      Nashville Predators  NHL  1998  2021   22  1731   852   656   60.0
 35        New Jersey Devils  NHL  1974  2021   46  3633  1534  1602  328.0
 36        New Jersey Devils  NHL  1982  2021   38  2993  1394  1211  219.0
 37         Colorado Rockies  NHL  1976  1982    6   480   113   281   86.0
 38       Kansas City Scouts  NHL  1974  1976    2   160    27   110   23.0
 39       New York Islanders  NHL  1972  2021   48  3788  1688  1587  347.0
 40         New York Rangers  NHL  1926  2021   94  6560  2883  2716  808.0
 41          Ottawa Senators  NHL  1992  2021   28  2195   971   940  115.0
 42      Philadelphia Flyers  NHL  1967  2021   53  4171  2079  1452  457.0
 43      Pittsburgh Penguins  NHL  1967  2021   53  4171  1903  1734  383.0
 44          San Jose Sharks  NHL  1991  2021   29  2274  1070   920  121.0
 45          St. Louis Blues  NHL  1967  2021   53  4173  1929  1645  432.0
 46      Tampa Bay Lightning  NHL  1992  2021   28  2194   985   947  112.0
 47      Toronto Maple Leafs  NHL  1917  2021  103  6786  3000  2829  783.0
 48      Toronto Maple Leafs  NHL  1926  2021   94  6560  2888  2720  778.0
 49     Toronto St. Patricks  NHL  1919  1926    7   186    94    87    5.0
 50           Toronto Arenas  NHL  1917  1919    2    40    18    22    0.0
 51        Vancouver Canucks  NHL  1970  2021   50  3945  1649  1746  391.0
 52     Vegas Golden Knights  NHL  2017  2021    4   291   173    94    NaN
 53      Washington Capitals  NHL  1974  2021   46  3633  1700  1467  303.0
 54            Winnipeg Jets  NHL  1999  2021   21  1651   724   729   45.0
 55            Winnipeg Jets  NHL  2011  2021   10   749   382   292    NaN
 56        Atlanta Thrashers  NHL  1999  2011   11   902   342   437   45.0

        OL   PTS   PTS%  Yrs Plyf  Div  Conf  Champ  St Cup
 0   180.0  2267  0.537        14    6     2    1.0     1.0
 1   143.0  1361  0.587        10    6     1    1.0     1.0
 2    37.0   906  0.476         4    0     1    0.0     0.0
 3   165.0  3101  0.479        20    1     0    0.0     0.0
 4    60.0   488  0.455         1    0     0    0.0     0.0
 5   105.0  1429  0.525         8    1     0    0.0     0.0
 6     NaN  1184  0.442        11    0     0    0.0     0.0
 7   191.0  7464  0.563        73   29     5    6.0     6.0
 8   167.0  4186  0.531        29    6     1    0.0     0.0
 9   150.0  4059  0.535        30    7     3    1.0     1.0
 10  150.0  3415  0.541        24    7     3    1.0     1.0
 11    NaN   644  0.506         6    0     0    0.0     0.0
 12  174.0  3159  0.489        15    4     2    1.0     1.0
 13  174.0  1914  0.528         7    3     2    1.0     1.0
 14    NaN  1245  0.438         8    1     0    0.0     0.0
 15  173.0  6611  0.504        63   17     4    6.0     6.0
 16  173.0  2858  0.534        22    6     4    3.0     3.0
 17    NaN  3753  0.483        41   11     0    3.0     3.0
 18  142.0  3411  0.527        25   11     2    2.0     2.0
 19  142.0  2257  0.571        16    9     2    2.0     2.0
 20    NaN  1154  0.459         9    2     0    0.0     0.0
 21  159.0  1548  0.494         6    0     0    0.0     0.0
 22  162.0  4305  0.516        33   10     4    1.0     1.0
 23  162.0  2455  0.582        16    8     3    1.0     1.0
 24    NaN  1850  0.449        17    2     1    0.0     0.0
 25  183.0  6976  0.532        64   29     6   11.0    11.0
 26  183.0  6738  0.535        62   29     6   11.0    11.0
 27    NaN    85  0.462         1    0     0    0.0     0.0
 28    NaN   153  0.435         1    0     0    0.0     0.0
 29  167.0  3367  0.520        22    6     7    5.0     5.0
 30  208.0  2128  0.505         6    2     1    0.0     0.0
 31  166.0  4098  0.491        30    1     3    2.0     2.0
 32  154.0  1727  0.551        10    1     0    0.0     0.0
 33  175.0  7958  0.586        84   37     3   25.0    23.0
 34  163.0  1927  0.557        13    2     1    0.0     0.0
 35  169.0  3565  0.491        23    9     5    3.0     3.0
 36  169.0  3176  0.531        22    9     5    3.0     3.0
 37    NaN   312  0.325         1    0     0    0.0     0.0
 38    NaN    77  0.241         0    0     0    0.0     0.0
 39  166.0  3889  0.513        26    6     3    4.0     4.0
 40  153.0  6727  0.513        60    8     2    4.0     4.0
 41  169.0  2226  0.507        16    4     1    0.0     0.0
 42  183.0  4798  0.575        40   16     4    2.0     2.0
 43  151.0  4340  0.520        35    9     6    5.0     5.0
 44  163.0  2424  0.533        21    6     1    0.0     0.0
 45  167.0  4457  0.534        43   10     1    1.0     1.0
 46  150.0  2232  0.509        12    4     3    2.0     2.0
 47  174.0  6957  0.513        69    8     0   13.0    13.0
 48  174.0  6728  0.513        65    7     0   11.0    11.0
 49    NaN   193  0.519         3    1     0    1.0     1.0
 50    NaN    36  0.450         1    0     0    1.0     1.0
 51  159.0  3848  0.488        28   10     3    0.0     0.0
 52   24.0   370  0.636         3    2     1    NaN     NaN
 53  163.0  3866  0.532        30   13     2    1.0     1.0
 54  153.0  1646  0.498         5    1     0    0.0     0.0
 55   75.0   839  0.560         4    0     0    0.0     0.0
 56   78.0   807  0.447         1    1     0    0.0     0.0  ,
                                 Franchise   Lg  From    To  Yrs   GP    W  \
 0                        Birmingham Bulls  WHA  1972  1979    7  556  242
 1                        Birmingham Bulls  WHA  1976  1979    3  241   99
 2                           Toronto Toros  WHA  1973  1976    3  237  108
 3                        Ottawa Nationals  WHA  1972  1973    1   78   35
 4                         Calgary Cowboys  WHA  1972  1977    5  395  174
 5                         Calgary Cowboys  WHA  1975  1977    2  161   72
 6                       Vancouver Blazers  WHA  1973  1975    2  156   64
 7                    Philadelphia Blazers  WHA  1972  1973    1   78   38
 8                         Chicago Cougars  WHA  1972  1975    3  234   94
 9                     Cincinnati Stingers  WHA  1975  1979    4  321  142
 10                       Cleveland Barons  NHL  1967  1978   11  858  229
 11                       Cleveland Barons  NHL  1976  1978    2  160   47
 12                California Golden Seals  NHL  1970  1976    6  472  116
 13                          Oakland Seals  NHL  1967  1970    3  226   66
 14                    Cleveland Crusaders  WHA  1972  1977    5  356  169
 15              Minnesota Fighting Saints  WHA  1976  1977    1   42   19
 16                    Cleveland Crusaders  WHA  1972  1976    4  314  150
 17                         Czechoslovakia  WHA  1977  1979    2   14    2
 18             Denver Spurs/Ottawa Civics  WHA  1975  1976    1   41   14
 19                        Edmonton Oilers  WHA  1972  1979    7  556  259
 20                        Edmonton Oilers  WHA  1973  1979    6  478  221
 21                         Alberta Oilers  WHA  1972  1973    1   78   38
 22                                Finland  WHA  1978  1979    1    1    0
 23                        Hamilton Tigers  NHL  1919  1925    6  150   51
 24                        Hamilton Tigers  NHL  1920  1925    5  126   47
 25          Quebec Athletic Club/Bulldogs  NHL  1919  1920    1   24    4
 26                          Houston Aeros  WHA  1972  1978    6  474  285
 27                    Indianapolis Racers  WHA  1974  1979    5  344  118
 28        Michigan Stags/Baltimore Blades  WHA  1972  1975    3  234   83
 29        Michigan Stags/Baltimore Blades  WHA  1974  1975    1   78   21
 30                     Los Angeles Sharks  WHA  1972  1974    2  156   62
 31              Minnesota Fighting Saints  WHA  1972  1976    4  293  154
 32                       Montreal Maroons  NHL  1924  1938   14  622  271
 33                     Montreal Wanderers  NHL  1917  1918    1    6    1
 34                    New England Whalers  WHA  1972  1979    7  555  281
 35                     New York Americans  NHL  1925  1942   17  784  255
 36                     Brooklyn Americans  NHL  1941  1942    1   48   16
 37                     New York Americans  NHL  1925  1941   16  736  239
 38                        Ottawa Senators  NHL  1917  1935   17  590  269
 39                       St. Louis Eagles  NHL  1934  1935    1   48   11
 40                        Ottawa Senators  NHL  1917  1934   16  542  258
 41                    Phoenix Roadrunners  WHA  1974  1977    3  238  106
 42                     Pittsburgh Pirates  NHL  1925  1931    6  256   71
 43                   Philadelphia Quakers  NHL  1930  1931    1   44    4
 44                     Pittsburgh Pirates  NHL  1925  1930    5  212   67
 45                       Quebec Nordiques  WHA  1972  1979    7  556  295
 46                     San Diego Mariners  WHA  1972  1977    5  395  184
 47                     San Diego Mariners  WHA  1974  1977    3  239  119
 48  New York Golden Blades/Jersey Knights  WHA  1973  1974    1   78   32
 49                       New York Raiders  WHA  1972  1973    1   78   33
 50                       Soviet All-Stars  WHA  1977  1979    2   14    7
 51                          Winnipeg Jets  WHA  1972  1979    7  555  302

       L    T  OL  PTS   PTS%  Yrs Plyf  Div  Conf  Champ  St Cup
 0   286   28 NaN  512  0.460         4    0     0      0       0
 1   129   13 NaN  211  0.438         1    0     0      0       0
 2   118   11 NaN  227  0.479         2    0     0      0       0
 3    39    4 NaN   74  0.474         1    0     0      0       0
 4   207   14 NaN  362  0.458         2    0     0      0       0
 5    78   11 NaN  155  0.481         1    0     0      0       0
 6    89    3 NaN  131  0.420         0    0     0      0       0
 7    40    0 NaN   76  0.487         1    0     0      0       0
 8   132    8 NaN  196  0.419         1    0     0      0       0
 9   164   15 NaN  299  0.466         2    0     0      0       0
 10  488  141 NaN  599  0.349         2    0     0      0       0
 11   87   26 NaN  120  0.375         0    0     0      0       0
 12  283   73 NaN  305  0.323         0    0     0      0       0
 13  118   42 NaN  174  0.385         2    0     0      0       0
 14  162   25 NaN  363  0.510         4    0     0      0       0
 15   18    5 NaN   43  0.512         0    0     0      0       0
 16  144   20 NaN  320  0.510         4    0     0      0       0
 17   10    2 NaN    6  0.214         0    0     0      0       0
 18   26    1 NaN   29  0.354         0    0     0      0       0
 19  273   24 NaN  542  0.487         5    1     0      0       0
 20  236   21 NaN  463  0.484         5    1     0      0       0
 21   37    3 NaN   79  0.506         0    0     0      0       0
 22    1    0 NaN    0  0.000         0    0     0      0       0
 23   98    1 NaN  103  0.343         0    1     0      0       0
 24   78    1 NaN   95  0.377         0    1     0      0       0
 25   20    0 NaN    8  0.167         0    0     0      0       0
 26  170   19 NaN  589  0.621         6    4     0      2       0
 27  202   24 NaN  260  0.378         2    1     0      0       0
 28  141   10 NaN  176  0.376         1    0     0      0       0
 29   53    4 NaN   46  0.295         0    0     0      0       0
 30   88    6 NaN  130  0.417         1    0     0      0       0
 31  127   12 NaN  320  0.546         3    0     0      0       0
 32  260   91 NaN  633  0.509        11    2     0      2       2
 33    5    0 NaN    2  0.167         0    0     0      0       0
 34  236   38 NaN  600  0.541         7    3     0      1       0
 35  402  127 NaN  637  0.406         5    0     0      0       0
 36   29    3 NaN   35  0.365         0    0     0      0       0
 37  373  124 NaN  602  0.409         5    0     0      0       0
 38  252   69 NaN  607  0.514         9    7     0      4       4
 39   31    6 NaN   28  0.292         0    0     0      0       0
 40  221   63 NaN  579  0.534         9    7     0      4       4
 41  114   18 NaN  230  0.483         2    0     0      0       0
 42  158   27 NaN  169  0.330         2    0     0      0       0
 43   36    4 NaN   12  0.136         0    0     0      0       0
 44  122   23 NaN  157  0.370         2    0     0      0       0
 45  237   24 NaN  614  0.552         5    2     0      1       0
 46  191   20 NaN  388  0.491         3    0     0      0       0
 47  106   14 NaN  252  0.527         3    0     0      0       0
 48   42    4 NaN   68  0.436         0    0     0      0       0
 49   43    2 NaN   68  0.436         0    0     0      0       0
 50    5    2 NaN   16  0.571         0    0     0      0       0
 51  227   26 NaN  630  0.568         6    3     0      3       0  ]

In [4]:
#Transform
df = team_tables[0]
df.head()

,Franchise,Lg,From,To,Yrs,GP,W,L,T,OL,PTS,PTS%,Yrs Plyf,Div,Conf,Champ,St Cup
0,Anaheim Ducks,NHL,1993,2021,27,2111,990,834,107.0,180.0,2267,0.537,14,6,2,1.0,1.0
1,Anaheim Ducks,NHL,2006,2021,15,1159,609,407,NaN,143.0,1361,0.587,10,6,1,1.0,1.0
2,Mighty Ducks of Anaheim,NHL,1993,2006,12,952,381,427,107.0,37.0,906,0.476,4,0,1,0.0,0.0
3,Arizona Coyotes,NHL,1979,2021,41,3234,1335,1468,266.0,165.0,3101,0.479,20,1,0,0.0,0.0
4,Arizona Coyotes,NHL,2014,2021,7,536,214,262,NaN,60.0,488,0.455,1,0,0,0.0,0.0

In [5]:
df1 = team_tables[1]
df1.head()

,Franchise,Lg,From,To,Yrs,GP,W,L,T,OL,PTS,PTS%,Yrs Plyf,Div,Conf,Champ,St Cup
0,Birmingham Bulls,WHA,1972,1979,7,556,242,286,28,NaN,512,0.460,4,0,0,0,0
1,Birmingham Bulls,WHA,1976,1979,3,241,99,129,13,NaN,211,0.438,1,0,0,0,0
2,Toronto Toros,WHA,1973,1976,3,237,108,118,11,NaN,227,0.479,2,0,0,0,0
3,Ottawa Nationals,WHA,1972,1973,1,78,35,39,4,NaN,74,0.474,1,0,0,0,0
4,Calgary Cowboys,WHA,1972,1977,5,395,174,207,14,NaN,362,0.458,2,0,0,0,0

In [6]:
#Merge both dataframes
merged_team_df = pd.merge(df, df1, how="outer")

In [7]:
filtered_merged_df = pd.DataFrame(merged_team_df, columns= ['Franchise', 'Lg', 'To', 'Yrs', 'GP', 'W', 'L', 'OL', 'PTS', 'Yrs Plyf', 'St Cup'])
#Rename Columns
filtered_merged_df.rename(columns = {'Franchise' : 'franchise',
                                     'Lg' : 'league', 
                                     'To' : 'ytd', 
                                     'Yrs' : 'years_active', 
                                     'GP' : 'games_played', 
                                     'W' : 'wins', 
                                     'L' : 'losses', 
                                     'OL' : 'overtime_losses', 
                                     'PTS' : 'points', 
                                     'Yrs Plyf' : 'playoff_appearences', 
                                     'St Cup': 'stanley_cup_wins'}, inplace=True)
filtered_merged_df

,franchise,league,ytd,years_active,games_played,wins,losses,overtime_losses,points,playoff_appearences,stanley_cup_wins
0,Anaheim Ducks,NHL,2021,27,2111,990,834,180.0,2267,14,1.0
1,Anaheim Ducks,NHL,2021,15,1159,609,407,143.0,1361,10,1.0
2,Mighty Ducks of Anaheim,NHL,2006,12,952,381,427,37.0,906,4,0.0
3,Arizona Coyotes,NHL,2021,41,3234,1335,1468,165.0,3101,20,0.0
4,Arizona Coyotes,NHL,2021,7,536,214,262,60.0,488,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...
104,San Diego Mariners,WHA,1977,3,239,119,106,NaN,252,3,0.0
105,New York Golden Blades/Jersey Knights,WHA,1974,1,78,32,42,NaN,68,0,0.0
106,New York Raiders,WHA,1973,1,78,33,43,NaN,68,0,0.0
107,Soviet All-Stars,WHA,1979,2,14,7,5,NaN,16,0,0.0
108,Winnipeg Jets,WHA,1979,7,555,302,227,NaN,630,6,0.0

In [8]:
#We only want teams that are still active today. Filter out the teams that are no longer active
filtered_merged_df = filtered_merged_df.loc[filtered_merged_df['ytd'] == 2021]
filtered_merged_df

,franchise,league,ytd,years_active,games_played,wins,losses,overtime_losses,points,playoff_appearences,stanley_cup_wins
0,Anaheim Ducks,NHL,2021,27,2111,990,834,180.0,2267,14,1.0
1,Anaheim Ducks,NHL,2021,15,1159,609,407,143.0,1361,10,1.0
3,Arizona Coyotes,NHL,2021,41,3234,1335,1468,165.0,3101,20,0.0
4,Arizona Coyotes,NHL,2021,7,536,214,262,60.0,488,1,0.0
7,Boston Bruins,NHL,2021,96,6626,3241,2403,191.0,7464,73,6.0
8,Buffalo Sabres,NHL,2021,50,3945,1805,1564,167.0,4186,29,0.0
9,Calgary Flames,NHL,2021,48,3790,1765,1496,150.0,4059,30,1.0
10,Calgary Flames,NHL,2021,40,3154,1497,1236,150.0,3415,24,1.0
12,Carolina Hurricanes,NHL,2021,41,3232,1361,1434,174.0,3159,15,1.0
13,Carolina Hurricanes,NHL,2021,23,1812,827,725,174.0,1914,7,1.0
15,Chicago Blackhawks,NHL,2021,94,6560,2812,2761,173.0,6611,63,6.0
16,Chicago Blackhawks,NHL,2021,34,2674,1244,1060,173.0,2858,22,3.0
18,Colorado Avalanche,NHL,2021,41,3234,1504,1327,142.0,3411,25,2.0
19,Colorado Avalanche,NHL,2021,25,1978,1007,728,142.0,2257,16,2.0
21,Columbus Blue Jackets,NHL,2021,20,1568,678,698,159.0,1548,6,0.0
22,Dallas Stars,NHL,2021,53,4171,1842,1708,162.0,4305,33,1.0
23,Dallas Stars,NHL,2021,27,2109,1084,738,162.0,2455,16,1.0
25,Detroit Red Wings,NHL,2021,94,6561,2989,2574,183.0,6976,64,11.0
26,Detroit Red Wings,NHL,2021,88,6293,2891,2446,183.0,6738,62,11.0
29,Edmonton Oilers,NHL,2021,41,3235,1469,1337,167.0,3367,22,5.0
30,Florida Panthers,NHL,2021,27,2109,889,870,208.0,2128,6,0.0
31,Los Angeles Kings,NHL,2021,53,4172,1754,1828,166.0,4098,30,2.0
32,Minnesota Wild,NHL,2021,20,1567,759,599,154.0,1727,10,0.0
33,Montreal Canadiens,NHL,2021,103,6787,3473,2302,175.0,7958,84,23.0
34,Nashville Predators,NHL,2021,22,1731,852,656,163.0,1927,13,0.0
35,New Jersey Devils,NHL,2021,46,3633,1534,1602,169.0,3565,23,3.0
36,New Jersey Devils,NHL,2021,38,2993,1394,1211,169.0,3176,22,3.0
39,New York Islanders,NHL,2021,48,3788,1688,1587,166.0,3889,26,4.0
40,New York Rangers,NHL,2021,94,6560,2883,2716,153.0,6727,60,4.0
41,Ottawa Senators,NHL,2021,28,2195,971,940,169.0,2226,16,0.0
42,Philadelphia Flyers,NHL,2021,53,4171,2079,1452,183.0,4798,40,2.0
43,Pittsburgh Penguins,NHL,2021,53,4171,1903,1734,151.0,4340,35,5.0
44,San Jose Sharks,NHL,2021,29,2274,1070,920,163.0,2424,21,0.0
45,St. Louis Blues,NHL,2021,53,4173,1929,1645,167.0,4457,43,1.0
46,Tampa Bay Lightning,NHL,2021,28,2194,985,947,150.0,2232,12,2.0
47,Toronto Maple Leafs,NHL,2021,103,6786,3000,2829,174.0,6957,69,13.0
48,Toronto Maple Leafs,NHL,2021,94,6560,2888,2720,174.0,6728,65,11.0
51,Vancouver Canucks,NHL,2021,50,3945,1649,1746,159.0,3848,28,0.0
52,Vegas Golden Knights,NHL,2021,4,291,173,94,24.0,370,3,NaN
53,Washington Capitals,NHL,2021,46,3633,1700,1467,163.0,3866,30,1.0
54,Winnipeg Jets,NHL,2021,21,1651,724,729,153.0,1646,5,0.0
55,Winnipeg Jets,NHL,2021,10,749,382,292,75.0,839,4,0.0

In [9]:
#If you notice, there are dupcliates. One of the duplicate rows is the total years that team was active.
#The row with fewer amount of years active is just an indicator that there was a change in ownership. 
filtered_merged_df1 = filtered_merged_df.drop_duplicates(subset='franchise', keep="first")

In [10]:
#Final clean-up.
filtered_merged_df1 = filtered_merged_df1.reset_index(drop=True)
filtered_merged_df1 = filtered_merged_df1.drop(columns = ['league', 'ytd'])
filtered_merged_df1['stanley_cup_wins'] = filtered_merged_df1['stanley_cup_wins'].fillna(0)
filtered_merged_df1

,franchise,years_active,games_played,wins,losses,overtime_losses,points,playoff_appearences,stanley_cup_wins
0,Anaheim Ducks,27,2111,990,834,180.0,2267,14,1.0
1,Arizona Coyotes,41,3234,1335,1468,165.0,3101,20,0.0
2,Boston Bruins,96,6626,3241,2403,191.0,7464,73,6.0
3,Buffalo Sabres,50,3945,1805,1564,167.0,4186,29,0.0
4,Calgary Flames,48,3790,1765,1496,150.0,4059,30,1.0
5,Carolina Hurricanes,41,3232,1361,1434,174.0,3159,15,1.0
6,Chicago Blackhawks,94,6560,2812,2761,173.0,6611,63,6.0
7,Colorado Avalanche,41,3234,1504,1327,142.0,3411,25,2.0
8,Columbus Blue Jackets,20,1568,678,698,159.0,1548,6,0.0
9,Dallas Stars,53,4171,1842,1708,162.0,4305,33,1.0
10,Detroit Red Wings,94,6561,2989,2574,183.0,6976,64,11.0
11,Edmonton Oilers,41,3235,1469,1337,167.0,3367,22,5.0
12,Florida Panthers,27,2109,889,870,208.0,2128,6,0.0
13,Los Angeles Kings,53,4172,1754,1828,166.0,4098,30,2.0
14,Minnesota Wild,20,1567,759,599,154.0,1727,10,0.0
15,Montreal Canadiens,103,6787,3473,2302,175.0,7958,84,23.0
16,Nashville Predators,22,1731,852,656,163.0,1927,13,0.0
17,New Jersey Devils,46,3633,1534,1602,169.0,3565,23,3.0
18,New York Islanders,48,3788,1688,1587,166.0,3889,26,4.0
19,New York Rangers,94,6560,2883,2716,153.0,6727,60,4.0
20,Ottawa Senators,28,2195,971,940,169.0,2226,16,0.0
21,Philadelphia Flyers,53,4171,2079,1452,183.0,4798,40,2.0
22,Pittsburgh Penguins,53,4171,1903,1734,151.0,4340,35,5.0
23,San Jose Sharks,29,2274,1070,920,163.0,2424,21,0.0
24,St. Louis Blues,53,4173,1929,1645,167.0,4457,43,1.0
25,Tampa Bay Lightning,28,2194,985,947,150.0,2232,12,2.0
26,Toronto Maple Leafs,103,6786,3000,2829,174.0,6957,69,13.0
27,Vancouver Canucks,50,3945,1649,1746,159.0,3848,28,0.0
28,Vegas Golden Knights,4,291,173,94,24.0,370,3,0.0
29,Washington Capitals,46,3633,1700,1467,163.0,3866,30,1.0
30,Winnipeg Jets,21,1651,724,729,153.0,1646,5,0.0

In [11]:
#Uploading the Corsica hockey html
url = 'https://www.corsicahockey.com/nhl/players/nhl-player-ratings-rankings'

In [12]:
#Extracting the data from the Corsica hockey html tables
tables = pd.read_html(url)
tables

[              Player                 Team Position  Rating  Ranking  GP  Age  \
 0     Leon Draisaitl      Edmonton Oilers        C   86.08        1  56   25
 1   Nathan MacKinnon   Colorado Avalanche        C   84.15        2  48   25
 2     Mika Zibanejad     New York Rangers        C   84.12        3  56   28
 3     David Pastrnak        Boston Bruins       LW   83.84        1  48   25
 4     Steven Stamkos  Tampa Bay Lightning        C   82.74        4  38   31
 ..               ...                  ...      ...     ...      ...  ..  ...
 95     Ryan O'Reilly       St Louis Blues        C   75.78       28  56   30
 96    Jakob Chychrun      Arizona Coyotes       LD   75.73       13  56   23
 97    Nikolaj Ehlers        Winnipeg Jets       LW   75.72       20  47   25
 98      Antti Raanta      Arizona Coyotes        G   75.68        2  12   32
 99        Jamie Benn         Dallas Stars       LW   75.55       21  52   31

    Shoots            Opponent
 0       L                 NaN
 1       R                 NaN
 2       R                 NaN
 3       R                 NaN
 4       R  New York Islanders
 ..    ...                 ...
 95      L                 NaN
 96      L                 NaN
 97      L                 NaN
 98      L                 NaN
 99      L                 NaN

 [100 rows x 9 columns]]

In [13]:
 type(tables)

list

In [14]:
corsica_df = tables[0]
corsica_df.head()

,Player,Team,Position,Rating,Ranking,GP,Age,Shoots,Opponent
0,Leon Draisaitl,Edmonton Oilers,C,86.08,1,56,25,L,NaN
1,Nathan MacKinnon,Colorado Avalanche,C,84.15,2,48,25,R,NaN
2,Mika Zibanejad,New York Rangers,C,84.12,3,56,28,R,NaN
3,David Pastrnak,Boston Bruins,LW,83.84,1,48,25,R,NaN
4,Steven Stamkos,Tampa Bay Lightning,C,82.74,4,38,31,R,New York Islanders

In [15]:
#replacing the NaN  with -
corsica_df.fillna('-')

,Player,Team,Position,Rating,Ranking,GP,Age,Shoots,Opponent
0,Leon Draisaitl,Edmonton Oilers,C,86.08,1,56,25,L,-
1,Nathan MacKinnon,Colorado Avalanche,C,84.15,2,48,25,R,-
2,Mika Zibanejad,New York Rangers,C,84.12,3,56,28,R,-
3,David Pastrnak,Boston Bruins,LW,83.84,1,48,25,R,-
4,Steven Stamkos,Tampa Bay Lightning,C,82.74,4,38,31,R,New York Islanders
...,...,...,...,...,...,...,...,...,...
95,Ryan O'Reilly,St Louis Blues,C,75.78,28,56,30,L,-
96,Jakob Chychrun,Arizona Coyotes,LD,75.73,13,56,23,L,-
97,Nikolaj Ehlers,Winnipeg Jets,LW,75.72,20,47,25,L,-
98,Antti Raanta,Arizona Coyotes,G,75.68,2,12,32,L,-
99,Jamie Benn,Dallas Stars,LW,75.55,21,52,31,L,-

In [16]:
#Drop the "Opponent" column
new_corsica_df = corsica_df.drop(columns="Opponent")
new_corsica_df

,Player,Team,Position,Rating,Ranking,GP,Age,Shoots
0,Leon Draisaitl,Edmonton Oilers,C,86.08,1,56,25,L
1,Nathan MacKinnon,Colorado Avalanche,C,84.15,2,48,25,R
2,Mika Zibanejad,New York Rangers,C,84.12,3,56,28,R
3,David Pastrnak,Boston Bruins,LW,83.84,1,48,25,R
4,Steven Stamkos,Tampa Bay Lightning,C,82.74,4,38,31,R
...,...,...,...,...,...,...,...,...
95,Ryan O'Reilly,St Louis Blues,C,75.78,28,56,30,L
96,Jakob Chychrun,Arizona Coyotes,LD,75.73,13,56,23,L
97,Nikolaj Ehlers,Winnipeg Jets,LW,75.72,20,47,25,L
98,Antti Raanta,Arizona Coyotes,G,75.68,2,12,32,L
99,Jamie Benn,Dallas Stars,LW,75.55,21,52,31,L

In [17]:
#Drop the "Ranking" column
new2_corsica_df = new_corsica_df.drop(columns="Ranking")
new2_corsica_df

              Player                 Team Position  Rating  GP  Age Shoots
0     Leon Draisaitl      Edmonton Oilers        C   86.08  56   25      L
1   Nathan MacKinnon   Colorado Avalanche        C   84.15  48   25      R
2     Mika Zibanejad     New York Rangers        C   84.12  56   28      R
3     David Pastrnak        Boston Bruins       LW   83.84  48   25      R
4     Steven Stamkos  Tampa Bay Lightning        C   82.74  38   31      R
..               ...                  ...      ...     ...  ..  ...    ...
95     Ryan O'Reilly       St Louis Blues        C   75.78  56   30      L
96    Jakob Chychrun      Arizona Coyotes       LD   75.73  56   23      L
97    Nikolaj Ehlers        Winnipeg Jets       LW   75.72  47   25      L
98      Antti Raanta      Arizona Coyotes        G   75.68  12   32      L
99        Jamie Benn         Dallas Stars       LW   75.55  52   31      L

[100 rows x 7 columns]

In [18]:
updtd_data_df = new2_corsica_df.rename(columns= {'Team': 'franchise', 'Player': 'player_name','Age': 'age', 'Rating': 'rating',
                                                 'Position': 'position', 'GP': 'games_played', 'Shoots': 'shoots_LR'})

updtd_data_df.columns

Index(['player_name', 'franchise', 'position', 'rating', 'games_played', 'age',
       'shoots_LR'],
      dtype='object')

In [20]:
player_data_df = updtd_data_df[['franchise', 'player_name', 'age', 'position', 'rating', 'games_played', 'shoots_LR']]
player_data_df

,franchise,player_name,age,position,rating,games_played,shoots_LR
0,Edmonton Oilers,Leon Draisaitl,25,C,86.08,56,L
1,Colorado Avalanche,Nathan MacKinnon,25,C,84.15,48,R
2,New York Rangers,Mika Zibanejad,28,C,84.12,56,R
3,Boston Bruins,David Pastrnak,25,LW,83.84,48,R
4,Tampa Bay Lightning,Steven Stamkos,31,C,82.74,38,R
...,...,...,...,...,...,...,...
95,St Louis Blues,Ryan O'Reilly,30,C,75.78,56,L
96,Arizona Coyotes,Jakob Chychrun,23,LD,75.73,56,L
97,Winnipeg Jets,Nikolaj Ehlers,25,LW,75.72,47,L
98,Arizona Coyotes,Antti Raanta,32,G,75.68,12,L
99,Dallas Stars,Jamie Benn,31,LW,75.55,52,L

In [21]:
#Load
from sqlalchemy import create_engine

In [22]:
rds_connection_string = "postgres:postgres@localhost:5432/NHL_Data"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [23]:
engine.table_names()

OperationalError: (psycopg2.OperationalError) FATAL:  database "NHL_Data" does not exist

(Background on this error at: http://sqlalche.me/e/13/e3q8)

In [ ]:
filtered_merged_df1.to_sql(name='team_history', con=engine, if_exists='append', index=False)

In [ ]:
pd.read_sql_query('select * from team_history', con=engine).head()